### PR TITLE
latest changes checked on OpenIndiana.

### PR DESCRIPTION
**Pull request by chincheta0815**
Hey,

I hope I got everything. Finally it compiles.
I took out the ASM stuff in libmediascan and the buildme.sh.
On my system it worked.

### CODE REVIEW

**Comment by fsbruva** [comment]
You removed code for all distros, and now the build is completely broken. We need to add logic in Makefile.PL, like what I added for Mac OS. See https://github.com/chincheta0815/libmediascan/pull/6

**Comment by chincheta0815** [comment]
What I wanted was to simply rebert to the state without any Bsymbolic, setting it to the agrundman times.

Maybe I oversaw a commit from you? Which commit is your latest?

**Comment by fsbruva** [comment]
You used the correct commit. The problem is that buildme.sh and the flags in Makefile.PL need to be in harmony. Linux and FreeBSD builds fail if buildme enables asm, but the -B symbolic flag is missing. So your change didn't fully revert to agrundman. I submitted a PR for the necessary changes to libmediascan so it can build on OS X.

**Comment by fsbruva** [comment]
Linux builds are still broken, because -Bsymbolic is missing, but buildme.sh has asm enabled. Makefile line 333 needs to be.... 
```
unshift @LDDLFLAGS, '-Wl,-Bsymbolic' unless ( $^O =~ /Darwin/i or $^O =~ /sun|solaris/i );
```

**Comment by fsbruva** [comment]
I have merged this, because it works on OS X, and FreeBSD.

However, can I ask why every file inside the libmediascan tarball has 0755 permissions? Does OpenIndiana require everything to be executable? Or can I safely revert the permissions for the C and Perl source files to 0644?

**Comment by chincheta0815** [comment]
No, OpenIndiana does not require 0755 on files. Only for e.g. the buildme.sh and directories there needs to be 0755. This is an issue with me. I once set 0755 and forget to revert that on some commits/repos locally. If you want me to do that just tell me. I mean my fault, my work ;o)

**Comment by fsbruva** [comment]
HA! I am glad it's not a major issue then.

I have already fixed it inside the tarball in my distro. I request you fix it for libmediascan-0.5. Hopefully we never need it. :-)

**Comment by chincheta0815** [comment]
@fsbruva I played a little bit with Appveyor for Windows-CI. Right now I got an issue with digitlist.cpp. That's something you already pathed. Would you mind reading the error message?

Don't wonder I used an old buildme.sh and have not adopted your new one... But first things first...
Once all compiles in Windows I thought of putting it into travis-ci and adopt all the changes.

Here the link to the repo:
https://github.com/chincheta0815/slimserver-vendor/tree/appveyor
Appveyor log:
https://ci.appveyor.com/project/chincheta0815/slimserver-vendor/builds/22832960

**Comment by fsbruva** [comment]
Looks like a library problem...
https://stackoverflow.com/questions/41844644/icu-58-undefined-reference-in-msys2-mingw64

**Pull request merged**
