### PR TITLE
latest changes.

### PR DESCRIPTION
**Pull request by chincheta0815**
Hey,

here are my latest changes that respect the different flavors of perl.
Hope this could be respected...

### CODE REVIEW

**Comment by fsbruva** [comment]
I already started working on this... so this merge will conflict with the branch once I push mine. I will incorporate your changes, and close this PR without merging. OK?

**Comment by chincheta0815** [comment]
totally okay.
when you have finished tell me abd i will add my line. they are not much, so it would be great to have them in.

**Comment by fsbruva** [comment]
I am done. You will likely need to rebase your local copy due to the conflicts. 

It would make it cleaner if we moved the case statement until AFTER the Perl checks. That way, we could put the -64int tests (and -m64 flag declaration) inside the SunOS case. What do you think? Find Perl first, followed by the tests for the other pre-requisites?

**Comment by chincheta0815** [comment]
> It would make it cleaner if we moved the case statement until AFTER the Perl checks. That way, we could put the -64int tests (and -m64 flag declaration) inside the SunOS case. What do you think? Find Perl first, followed by the tests for the other pre-requisites?

I like that idea of cleaning up and thought the same. Another thing I was thinking about: Is it still necessary to use all these perl checks? It would be far more cleaner to simply use the latest if-statement that is calles when PERL_BIN is empty or a custom perl is selected. As of today, the more perls are supported the longer the checks for the perls become...

Right now I would say this would work as long as it is okay to use the perl in PATH. Otherwise one could use the CMD line args...

What's your opinion?
I would start changing it, if you like the idea.
BTW: 
- What is the actual branch? test/ or devel/ ?
- Do you know how the Win modules are built? Then I would try to implement the Win checks on maybe appveyor...

**Comment by fsbruva** [comment]
I agree about all the Perl tests. Either use Perl that's in PATH, or the user specifies it as CMD line argument.

Let's use devel/7.9. The "Tests" branch failed pretty miserably last night. I tried updating 2 or 3 modules, and was in dependency hell.

I have no idea how the Win modules are built.

**Comment by fsbruva** [comment]
Travis also has windows images for c++ builds, and they have Chocolatey to manage packages (just like appveyor). I will experiment with that this weekend so our commits don't clash.

Also, I am debugging an issue with the updated SQLite not passing tests on Perl 5.8.9. I am sorry if I cause conflicts with your commits with that.

**Comment by fsbruva** [comment]
@chincheta0815 
Please see my latest changes to the devel/7.9 branch - I performed the code refactor, and updated the documentation. The build worked for me on FreeBSD, we'll see how it fares on Travis. Can you please check if it works for Solaris?

**Comment by fsbruva** [comment]
@chincheta0815 
Did you get a chance to try this with Solaris? I have been holding off on submitting this as a PR to Michael until I heard from you.

**Comment by chincheta0815** [comment]
I had some issues with my system. Sorry.
Then I had to change some stuff.
It worked, but I am not shure if the latest version is in my git.
I will check o saturrday/sunday and tell you, if that's okay.

**Comment by fsbruva** [comment]
That's fine. I pushed a few more commits, but nothing that should impact your system.

If you want, you can do another PR to the devel/7.9 branch, or just do a gist of the changes and I will incorporate them.

**Comment by chincheta0815** [comment]
Well, I got a small issue with the compiler flags "-m32". On a frist shot it just throws the message, Therfore, I want to be safe that it is just the message. For the libmediascan with asm I thin I will disable that on SunOS. It does not seem to be stable... I thave to test and come back to you . Is that okay?

**Comment by fsbruva** [comment]
Yes - that's fine. Made a few changes last night to my public/7.9 branch to reflect what i saw on your devel/7.9 branch. I will freeze mine until you get back to me.

**Pull request closed without merging**
