### PR TITLE
libmediascan-0.3

### PR DESCRIPTION
**Pull request by chincheta0815**
Hopefully this works now.

### CODE REVIEW

**Comment by chincheta0815** [comment]
Sorry for the conflicts. I also changed some things in the buildme.sh for upgraded Perl stuff...

**Comment by fsbruva** [comment]
@chincheta0815 .

Please hold off on additional commits on this branch for now. I am having trouble managing and adjudicating all the conflicts. I will merge this into my devel/7.9 branch. I request you fork off that, and any additional commits be made there. I will also close the other PR.

**Comment by fsbruva** [comment]
@chincheta0815  - Alright, I've merged this into my existing devel/7.9 branch. You can see the Travis status:
https://travis-ci.com/fsbruva/slimserver-vendor 

Where you modified some of the library tests to use "if", I had used the `-o errexit` for bash. I adopted your syntax.

**Comment by fsbruva** [comment]
@chincheta0815 - Your edits works on FreeBSD, but fails on Travis on Ubuntu AND OSx. I am working on debugging, but I am extremely vexed.

**Comment by fsbruva** [comment]
@chincheta0815 - I merged your results (cleanly) into a copy of public/7.9. Here is what happens when Travis tries to build it: https://travis-ci.com/fsbruva/slimserver-vendor/builds/94875896 

Thoughts?

**Comment by chincheta0815** [comment]
> @chincheta0815 - Your edits works on FreeBSD, but fails on Travis on Ubuntu AND OSx. I am working on debugging, but I am extremely vexed.

Sorry for bothering and making you angry... Could you tell me what went wrong with ubuntu and OSX?

**Comment by chincheta0815** [comment]
> @chincheta0815 - I merged your results (cleanly) into a copy of public/7.9. Here is what happens when Travis tries to build it: https://travis-ci.com/fsbruva/slimserver-vendor/builds/94875896
> 
> Thoughts?

I have to have a closer look in to this. The error log does not show much information and the build stop quite early... Why did you start the script with "bash -o errexit buildme.sh" and not just ./buildme.sh?
There is an option I do not remember that tell bash to show each line it executes. It's "set <something>" I will check that and send you the info... Could take a little as I am busy right now.

**Comment by chincheta0815** [comment]
Try "set -x" at the beginning of the buildme.sh. This will print each line bash executes. Maybe this reveals the offending line.

**Comment by fsbruva** [comment]
@chincheta0815 I am sorry for my poor choice of words. I was not actually vexed. In reality, I was stymied. I was stuck, out of ideas and in need of troubleshooting assistance. At first I thought it was some regression I had introduced during the manual merge into devel/7.9. Then I discovered the error existed in your PR.

I used the -o errexit because when I first started using Travis, it was reporting that builds had passed, even though one of the simple commands within the script had failed. It's the same as setting -e prior to running the script.

I will add the -x option to the fsbruva:devel/7.9_merge branch.

**Comment by fsbruva** [comment]
@chincheta0815 
Here is the build I just triggered, with the xtrace option set (same as -x). https://travis-ci.com/fsbruva/slimserver-vendor/builds/94901273

**Comment by fsbruva** [comment]
@chincheta0815
Good news! Your suggestion was right on target.

The problem is that $MAKE never gets defined for anything other than FreeBSD or Solaris. The *) of the case only gets executed if none of the other cases match. I will move the code to before the case.

**Comment by chincheta0815** [comment]
That was my fault, sorry. No linux here..

Another idea could be to set a default $MAKE before the case statement by looking into $PATH and/or define $MAKE in every case (for Linux and remove the *). Only issue: How treat different linuxes like ReadyNAS...

**Comment by fsbruva** [comment]
I was thinking of a default before the case. This follows the existing convention for CC. The ReadyNAS question is already solved. If make exists in /usr/local, prefer that as the default. This preserves the existing behavior. Alternatively, we could just say 
```
MAKE=`which make`
```

However, that would require the correct order of locations within PATH. The existing code is sufficient.

**Comment by fsbruva** [comment]
@chincheta0815
Good news. I was able to merge your PR into devel/7.9, and then successfully build on all travis targets! https://travis-ci.com/fsbruva/slimserver-vendor/builds/95455045

I will be doing my VM test builds (Centos, Debian, multiple FreeBSD versions and Perl combos) tomorrow and Saturday. Can you please test out my devel/7.9 branch, and make sure it works for solaris? I want to ensure I didn't butcher your work during the merge.

**Pull request merged**
